// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("TodoList");

function make(todos, completed, markComplete, markIncomplete, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var completedTodos = $$Array.map((function (todo) {
                      return React.createElement("li", {
                                  key: todo
                                }, React.createElement("label", undefined, React.createElement("button", {
                                          className: "checkbox completed",
                                          onClick: (function (_event) {
                                              return Curry._1(markIncomplete, todo);
                                            })
                                        }, "Mark Complete"), todo));
                    }), $$Array.of_list(completed));
              var incompleteTodos = $$Array.map((function (todo) {
                      return React.createElement("li", {
                                  key: todo
                                }, React.createElement("label", undefined, React.createElement("button", {
                                          className: "checkbox",
                                          onClick: (function (_event) {
                                              return Curry._1(markComplete, todo);
                                            })
                                        }, "Mark Complete"), todo));
                    }), $$Array.of_list(todos));
              var match = incompleteTodos.length !== 0;
              var match$1 = completedTodos.length !== 0 || incompleteTodos.length === 0;
              return React.createElement(React.Fragment, undefined, React.createElement("ul", undefined, match ? incompleteTodos : "Wahoo! All done! \xf0\x9f\x8e\x89"), React.createElement("ul", undefined, match$1 ? completedTodos : "Let's get something done!"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
