// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("TodoInput");

function make($staropt$star, addTodo, _children) {
  var placeholder = $staropt$star !== undefined ? $staropt$star : "Conquer the world";
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("input", {
                          placeholder: placeholder,
                          value: self[/* state */1][/* inputValue */0],
                          onKeyPress: (function ($$event) {
                              var key = $$event.key;
                              if (key === "Enter") {
                                return Curry._1(self[/* send */3], /* CreateTodo */Block.__(1, [self[/* state */1][/* inputValue */0]]));
                              } else {
                                return 0;
                              }
                            }),
                          onChange: (function ($$event) {
                              return Curry._1(self[/* send */3], /* Change */Block.__(0, [$$event.target.value]));
                            })
                        });
            }),
          /* initialState */(function (param) {
              return /* record */[/* inputValue */""];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              if (action.tag) {
                Curry._1(addTodo, action[0]);
                return /* Update */Block.__(0, [/* record */[/* inputValue */""]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* inputValue */action[0]]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
