// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TodoList$ReactTemplate = require("./TodoList.bs.js");
var TodoInput$ReactTemplate = require("./TodoInput.bs.js");

var component = ReasonReact.reducerComponent("TodoApp");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "app"
                        }, ReasonReact.element(undefined, undefined, TodoInput$ReactTemplate.make(undefined, (function (todo) {
                                    return Curry._1(self[/* send */3], /* AddTodo */Block.__(0, [todo]));
                                  }), /* array */[])), ReasonReact.element(undefined, undefined, TodoList$ReactTemplate.make(self[/* state */1][/* todos */0], self[/* state */1][/* completed */1], (function (todo) {
                                    return Curry._1(self[/* send */3], /* CompleteTodo */Block.__(1, [todo]));
                                  }), (function (todo) {
                                    return Curry._1(self[/* send */3], /* UncompleteTodo */Block.__(2, [todo]));
                                  }), /* array */[])));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* todos : [] */0,
                      /* completed : [] */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* todos : :: */[
                                  action[0],
                                  state[/* todos */0]
                                ],
                                /* completed */state[/* completed */1]
                              ]]);
                case 1 : 
                    var todo = action[0];
                    return /* Update */Block.__(0, [/* record */[
                                /* todos */List.filter((function (el) {
                                          return todo !== el;
                                        }))(state[/* todos */0]),
                                /* completed : :: */[
                                  List.find((function (el) {
                                          return el === todo;
                                        }), state[/* todos */0]),
                                  state[/* completed */1]
                                ]
                              ]]);
                case 2 : 
                    var todo$1 = action[0];
                    return /* Update */Block.__(0, [/* record */[
                                /* todos : :: */[
                                  List.find((function (el) {
                                          return el === todo$1;
                                        }), state[/* completed */1]),
                                  state[/* todos */0]
                                ],
                                /* completed */List.filter((function (el) {
                                          return todo$1 !== el;
                                        }))(state[/* completed */1])
                              ]]);
                
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
